name: Upload Python Package to PyPi

on:
  release:
    types: [published]

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Build dists
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Upload dists
        uses: actions/upload-artifact@v3
        with:
          name: eburger-dists
          path: dist/

  publish:
    runs-on: ubuntu-latest

    environment: release
    
    permissions:
      id-token: write
      contents: write
    
    needs:
      - build-release
    
    steps:
      - name: Fetch dists
        uses: actions/download-artifact@v3
        with:
          name: eburger-dists
          path: dist/

      - name: publish
        uses: pypa/gh-action-pypi-publish@v1.8.10