name: Upload Python Package to PyPi

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
      
    - name: Build package
      run: python -m build

  deploy:
    needs:
      - build

    environment: release
    
    permissions:
      id-token: write
      contents: write 

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@v1.8.10