name: pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule: [ cron: "0 7 * * 2" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv /tmp/pytest-env
          source /tmp/pytest-env/bin/activate
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install pytest
          python -m pip install .

      - name: Run pytest
        run: |
          source /tmp/pytest-env/bin/activate
          pytest -s tests/
